version: "3.5"
services:
  anisearchkomga:
    container_name: anisearchkomga
    image: pfuenzle/anisearchkomga
    environment:
      - KOMGAURL=https://komga.com
      - KOMGAEMAIL=adminemail@komga.com
      - KOMGAPASSWORD=12345
      - LANGUAGE=German
      - KEEPPROGRESS=True
    volumes:
      - ./mangas.progress:/app/mangas.progress